services:
  f2pool-aleo-prover:
    build: .
    environment:
      - WORKER=
    network_mode: "host"
    deploy:
      resources:
          reservations:
              devices:
                  - driver: "nvidia"
                    count: "all"
                    capabilities: ["gpu"]
