# Not Change
chain:
  # Not Change
  endpoint: "grpc-testnet.prover.xyz:80"
  # Not Change
  chain_id: "cysicmint_9001-1"
  # Not Change
  gas_coin: "CYS"
  # Not Change
  gas_price: 10
  # Modify Here：! Your Address (EVM) submitted to claim rewards

######################
#   chain  setting   #
######################
asset_path: /root/.cysic/assets
claim_reward_address: __EVM_ADDRESS__

server:
  # don't modify this
  cysic_endpoint: "https://ws.prover.xyz"
available_task_type:
  - scroll
  - ethProof

task_config:
  eth_proof:
    endpoint: __ETH_PROOF_ENDPOINT__
