services:
  zkwork-aleo-prover:
    build: .
    environment:
      - ADDRESS=
    network_mode: "host"
    deploy:
      resources:
          reservations:
              devices:
                  - driver: "nvidia"
                    count: "all"
                    capabilities: ["gpu"]
