services:
  prover:
    build: .
    environment:
      - ADDRESS=
      - WORKER_NAME=
      - AGENT_HOST=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
          reservations:
              devices:
                  - driver: "nvidia"
                    count: "all"
                    capabilities: ["gpu"]
