name: Build and push `aleo-cysic-agent` docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - aleo/cysic/agent/**
      - .github/workflows/aleo-cysic-agent.yml
  pull_request:
    branches:
      - main
    paths:
      - aleo/cysic/agent/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          file: aleo/cysic/agent/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: aleo/cysic/agent
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cysic-aleo-agent:latest
            ${{ secrets.DOCKER_USERNAME }}/cysic-aleo-agent:v1
            ${{ secrets.DOCKER_USERNAME }}/cysic-aleo-miner-agent:latest
            ${{ secrets.DOCKER_USERNAME }}/cysic-aleo-miner-agent:v1
